package generators

import (
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/the-trybe/forge-deploy-cli/pkg/models"
)

// GenerateForgeDeployYAML generates the forge-deploy.yml file content
func GenerateForgeDeployYAML(config *models.DeploymentConfig) (string, error) {
	// Marshal to YAML
	data, err := yaml.Marshal(config)
	if err != nil {
		return "", fmt.Errorf("failed to marshal config: %w", err)
	}

	// Add header comment
	header := `# Laravel Forge Deployment Configuration
# Generated by forge-deploy-cli
# See: https://github.com/the-trybe/deploy-to-laravel-forge

`

	return header + string(data), nil
}

// GenerateGitHubWorkflow generates the GitHub Actions workflow file content
func GenerateGitHubWorkflow(config *models.DeploymentConfig, workflowName, triggerBranch string, forgeConfigFileName string) string {
	workflow := fmt.Sprintf(`# GitHub Actions Workflow for Laravel Forge Deployment
# Generated by forge-deploy-cli

name: %s

on:
  push:
    branches: [%s]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Laravel Forge
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Forge
        uses: the-trybe/deploy-to-laravel-forge@v2
        with:
          forge_api_token: ${{ secrets.FORGE_API_TOKEN }}
          deployment_file: %s

        #secrets: |
          #SECRET_VAR=${{ secrets.SECRET_VAR }}

`, workflowName, triggerBranch, forgeConfigFileName)

	return workflow
}

// sortStrings is a simple sort for string slices
func sortStrings(arr []string) {
	for i := 0; i < len(arr)-1; i++ {
		for j := i + 1; j < len(arr); j++ {
			if arr[i] > arr[j] {
				arr[i], arr[j] = arr[j], arr[i]
			}
		}
	}
}
